name: getx_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # warning on 3.0.0
  bruno: ^2.2.0
  flutter_screenutil: ^5.4.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  lottie: ^1.3.0

  image_picker: ^0.8.5+3
  # warning on 3.0.0
  cached_network_image: ^3.2.0
  # warning on 3.0.0
  pull_to_refresh: ^2.0.0
  webview_flutter: ^2.8.0
  wakelock: ^0.6.1+2
  fijkplayer: ^0.10.1

  get: ^4.6.1
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  dio: ^4.0.6
  dio_cache_interceptor: ^3.2.6
  json_annotation: ^4.5.0
  path_provider: ^2.0.9
  shanyan:
    git:
      url: https://gitee.com/TaXiangZhiKe/CLShanYan_Flutter.git
      path: shanyan
      ref: v2.3.3.5
  flutter:
    sdk: flutter

dev_dependencies:
  json_model: ^1.0.0
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/img/
    - assets/svgs/
    - assets/lotties/lottie_common_load.json
    - assets/lotties/refresh_empty_page.json
    - assets/lotties/refresh_head_loading.json
    - assets/lotties/refresh_footer.json
    - assets/lotties/page_loading_anim.json
    - assets/lotties/refresh_empty_page.json
    - assets/lotties/refresh_error.json
  fonts:
    - family: AntdIcons
      fonts:
        - asset: assets/fonts/AntdIcons.ttf
